### ISSUE TITLE
name 'set_module_tensor_to_device' is not defined

### ISSUE THREAD

**Issue by CoryBloyd** [kijai/ComfyUI-ELLA-wrapper#10]
Fresh install of ComfyUI via Pinokio
Added ComfyUI-ELLA-wrapper via ComfyUIManager
Closed Pinokio
F:\pinokio\api\comfyui.git\app\env\Scripts\python.exe  -m pip install -r custom_nodes\ComfyUI-ELLA-wrapper\requirements.txt
Setup up a minimal workflow matching the example from the top of README.md
---
Error occurred when executing ella_model_loader:

name 'set_module_tensor_to_device' is not defined

File "F:\pinokio\api\comfyui.git\app\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\pinokio\api\comfyui.git\app\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\pinokio\api\comfyui.git\app\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-ELLA-wrapper\nodes.py", line 160, in loadmodel
set_module_tensor_to_device(new_vae, key, device=device, dtype=dtype, value=converted_vae[key])

**Comment by kijai** [comment]
Forgot to put accelerate in requirements, and it should also work without it now. I recommend reinstalling or installing accelerate though, as it speeds up the model loading a lot.

**Comment by CoryBloyd** [comment]
Update all in ComfyUI Manager "Successfully installed accelerate-0.29.2"
Restart Pinokio.
Confirmed fixed!

Thanks for the awesome plugin!
