### ISSUE TITLE
"addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by Reledia** [kijai/ComfyUI-ELLA-wrapper#2]
Trying to run the example.json, but this is the only thing I get when running the sampler node

**Comment by kijai** [comment]
Which GPU? That error is usually associated when trying to run something on cpu with fp16. I've only tested on cuda so far.

**Comment by Reledia** [comment]
Apparently it got resolved with a `git pull`. I have no problems now. Still thanks for the time
